{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ark-cluster.serviceAccountName" . }}
  labels:
    {{- include "ark-cluster.labels" . | nindent 4 }}
    {{- include "ark-cluster.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    {{- include "ark-cluster.annotations" (dict "annotations" .Values.commonAnnotations "context" $) | indent 4 }}
    {{- include "ark-cluster.annotations" (dict "annotations" .Values.serviceAccount.annotations "context" $) | indent 4 }}
{{- end }}
