apiVersion: v2
name: ark-cluster
version: 0.1.6
description: A Helm chart for an Ark - Survival Evolved cluster
type: application
appVersion: latest
home: https://store.steampowered.com/app/346110/ARK_Survival_Evolved/
icon: https://raw.githubusercontent.com/DrPsychick/ark-server-charts/master/charts/ark-cluster/icon.png
keywords:
  - game
  - server
  - steam
  - ark
sources:
  - https://github.com/DrPsychick/ark-server-charts
maintainers:
  - name: DrPsychick
    email: drpsychick@drsick.net
    url: https://github.com/DrPsychick
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/SickHub/arkserver
    - name: Image DockerHub
      url: https://hub.docker.com/r/drpsychick/arkserver
